Hygrometry regulation
botand/Herbarium-embedded pull request #11
Opened 2021-12-07 00:54 UTC by CharlesChaum

Alors j'ai ajouté la classe de régulation comme on l'a conçue. Je fait une PR maintenant pour qu'on valide ce travail :)

2021-12-08 01:30 UTC, apomalyn requested changes

2021-12-08 01:30 UTC, apomalyn commented on src/controllers/hygrometry_regulation_controller.py
> +            hygro_val = ADCService.instance().get_plant_hygrometry_value(i)
Plutot que d'utiliser `ADCService.instance()` a chaque fois pose le comme une variable de la classe.

2021-12-08 01:30 UTC, apomalyn commented on src/controllers/hygrometry_regulation_controller.py
> +            ((hygro_val >= (self._last_read(i) - self._delta_detection)) && (hygro_val <= (self._last_read(i) + self._delta_detection))):
```suggestion
            difference_avg = hygro_val - self._average[i]
            difference_last_read = hygro_val - self._last_read[i]
            if ((difference_avg <= - self._delta_detection) || (difference_avg >= self._delta_detection)) && 
            ((difference_last_read >= - self._delta_detection) && (difference_last_read <= self._delta_detection)):

```

Ca devrait marcher ca normalement :thinking: et ca simplified la lisibilite

2021-12-08 01:30 UTC, apomalyn commented on src/controllers/hygrometry_regulation_controller.py
> +                if hygro_val >= (self._average(i) + self._delta_detection)
```suggestion
                if hygro_val >= (self._average[i] + self._delta_detection):

```

2021-12-08 01:30 UTC, apomalyn commented on src/controllers/hygrometry_regulation_controller.py
> +                    DatabaseService.instance().execute(INSERT_NEW_PLANT, i)
Meme chose que pour l'ADC service met le en variable de classe :smile:

2021-12-08 01:30 UTC, apomalyn commented on src/controllers/hygrometry_regulation_controller.py
> +                    DatabaseService.instance().execute(REMOVE_PLANT, plants(i).uuid(), i)
```suggestion
                else:
                    # Retirer de la DB
                    DatabaseService.instance().execute(REMOVE_PLANT, plants[i].uuid, i)

```

uuid est une propriete de `Plant` pas besoin de mettre de parentheses

2021-12-08 01:30 UTC, apomalyn commented on src/controllers/hygrometry_regulation_controller.py
> +            self._last_read(i) = hygro_val
```suggestion
                self._cummulative[i] = self._last_read[i]
                self._nb_sample[i] = 1

            self._cummulative[i] += hygro_val
            self._nb_sample[i] += 1
            self._last_read[i] = hygro_val

```

2021-12-08 01:30 UTC, apomalyn commented on src/controllers/hygrometry_regulation_controller.py
> +                self._nb_sample(i) = 0
```suggestion
            if self._nb_sample[i] == self._max_sample_regulation:
                self._average[i] = self._cummulative[i] / self._nb_sample[i]
                if plant.moisture_goal != None
                    # Dataase Communication
                    DatabaseService.instance().execute(INSERT_MOISTURE_LEVEL_FOR_PLANT, self._average[i], plants[i].uuid)
                    # Regulation
                    if self.average(i) < plat.moisture_goal()
                        self._query_shot(i)
                self._cummulative(i) = 0
                self._nb_sample(i) = 0              

```

2021-12-08 01:30 UTC, apomalyn commented on src/controllers/hygrometry_regulation_controller.py
> +                DatabaseService.instance().execute(INSERT_VALVE_ORDER, plants(self._shot_query_queue[0]).uuid(), "open")
```suggestion
                DatabaseService.instance().execute(INSERT_VALVE_ORDER, plants(self._shot_query_queue[0]).uuid, "open")

```

2021-12-08 01:30 UTC, apomalyn commented on src/controllers/hygrometry_regulation_controller.py
> +                PumpService.instance().set_speed(self._pump_seed)
Meme chose, hesite pas a poser les services dans des variables de la classe ca evite un appel de fonction a chaque fois :smile:

2021-12-08 01:30 UTC, apomalyn commented on src/controllers/hygrometry_regulation_controller.py
> +                    DatabaseService.instance().execute(INSERT_VALVE_ORDER, plants(self._shot_query_queue[0]).uuid(), "close")
```suggestion
                    DatabaseService.instance().execute(INSERT_VALVE_ORDER, plants(self._shot_query_queue[0]).uuid, "close")

```

2021-12-08 01:30 UTC, apomalyn commented on src/services/adc_service.py
> +    def __init__(self, config):
Est-ce que tu pourrais mettre dans la docstring ce qu'est `config` stp. Je dirais que tu veux ici mettre la "key" pour acceder a la section de la config qui est pour l'ADC c'est ca?

D'ailleurs quelques lignes plus haut (l.38) tu ne donne pas de parametre au init ^^'

2021-12-09 18:56 UTC, CharlesChaum reviewed
Done

2021-12-09 19:15 UTC, merged