Valve, Pompe et LED Strip, ils débarquent dans les bacs !
botand/Herbarium-embedded pull request #6
Opened 2021-11-09 20:43 UTC by CharlesChaum

2021-11-10 13:58 UTC, apomalyn requested changes
Some little changes but otherwise it's good!

2021-11-10 13:58 UTC, apomalyn commented on TileNumbering.md
> +# Tile Numbering
Est-ce que tu pourrais mettre ça dans un dossier 'docs' s'il te plait? ^^

2021-11-10 13:58 UTC, apomalyn commented on src/__main__.py
> +from src.utils import config, config_ble, led_utils, get_logger, time_in_millisecond
```suggestion
from src.utils import (
    config, 
    config_ble,
    led_utils, 
    get_logger, 
    time_in_millisecond
)
```

Histoire d'avoir partout les même types d'import.

2021-11-10 13:58 UTC, apomalyn commented on src/services/pump_service.py
> +        :param config: configuration file to use.
```suggestion
        :param config: configuration to use.
```

2021-11-10 13:58 UTC, apomalyn commented on src/services/pump_service.py
> +        :param speed: in percentage [0.0-100.0]
```suggestion
        :param speed: in percentage [0.0-100.0]
        :type speed: double
```

2021-11-10 13:58 UTC, apomalyn commented on src/services/pump_service.py
> +        :param speed: in percentage [0.0-100.0]
```suggestion
        :param speed: in percentage [0.0-100.0]
        :type speed: double
```

2021-11-10 13:58 UTC, apomalyn commented on src/services/valve_service.py
> +        :param config: configuration file to use.
```suggestion
        :param config: configuration to use.
```

2021-11-10 13:58 UTC, apomalyn commented on src/services/valve_service.py
> +        :param valve_nb: decimal selected valve [0-15]
```suggestion
        :param valve_nb: decimal selected valve [0-15]
        :type valve_nb: int
```

2021-11-10 13:58 UTC, apomalyn commented on src/services/valve_service.py
> +        :param tile_nb : tile number [0-15]
```suggestion
        :param tile_nb : tile number [0-15]
        :type tile_nb: int
```

2021-11-10 13:58 UTC, apomalyn commented on src/services/valve_service.py
> +            "close": config[_VALVE_POSITION_OFF],
si il y a moyen de passer "open" et "close" comme des constante déclaré plus haut ce serait mieux.

2021-11-11 02:57 UTC, CharlesChaum commented on TileNumbering.md
> +# Tile Numbering
Il faut encore que je valide l'ordre mais oui

2021-11-11 03:07 UTC, CharlesChaum commented on src/services/valve_service.py
> +            "close": config[_VALVE_POSITION_OFF],
Je ne suis pas sur que ce soit une bonne chose, c'est justement une déclaration de constante dans un dictionnaire pour que je puisse faire référence à "open" et "close" pour appliquer automatiquement les bonnes valeurs dans la méthode update :)
Bref comme ca c'est très bien :)

2021-11-11 03:24 UTC, CharlesChaum commented on TileNumbering.md
> +# Tile Numbering
Done

2021-11-11 03:27 UTC, CharlesChaum reviewed
good

2021-11-11 19:01 UTC, apomalyn approved these changes
LGTM

2021-11-11 22:52 UTC, merged